<html>
<head>
<TITLE>孙洪伟电话本管理系统</TITLE>
<link rel="stylesheet" type="text/css" href="/css/index.css"/>
</head>
<body>
<div class='login'>
<h1 class='h1'>孙洪伟的电话本管理系统</h1>
<form action="/index/show" method='post'>
<table>
<tr><td>用户名:</td><td><input type="text" name="username"><td></tr>
<tr><td>密&nbsp;&nbsp;码:</td><td><input type="password" name="password"><td></tr>
<tr><td>&nbsp;&nbsp;<input type="submit" value="登陆"/>&nbsp;&nbsp;&nbsp;&nbsp;</td><td><input type="reset" value="重新填写"/></td></tr>
</table>
</form>
</div>
</body>
</html>