<html>
<head>
<title>添加联系人</title>
<link rel="stylesheet" type="text/css" href="/css/guanli.css"/>
</head>
<body>
<div class="tianjia">
<h1><center>添加联系人</center></h1>
<form action="/admin/tianjia" method="post">
<table>
<tr><td>姓名</td><td><input type="text" name="姓名"></td></tr>
<tr><td>电话</td><td><input type="text" name="电话"></td></tr>
<tr><td>联系人关系</td><td>
<textarea rows='5px' cols='30px' name="联系人关系"></textarea>
</td></tr>
<tr><td><input type="submit" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><input type="reset" value="重新填写"></td></tr>
</table>
</form>
</div>
</body>
</html>